version: '2'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  sunshare:
    image: nicohkptn/sunshare
    container_name: sunshare
    depends_on:
      - mongo
    environment:
      - ENV=DEV
    ports:
      - "127.0.0.1:7777:3000"
    volumes:
      - .:/app
